### ISSUE TITLE
Bloodletting Skill for Bloodhunter

### ISSUE THREAD

**Issue by EwayWen** [EwayWen/CalcutrollsAbilityOverhaul#11]
Description: Necromancer utility skill that removes debuffs and heals at some cost. Creates a small blood pool.

Ability: Death
ActionPoints: 1
Cooldown: 4
SkillProperties: CON_DOWN_1,100,3
TargetRadius: 13
MemorizationRequirements: Necromancy 1
CanTargetCharacters: Yes
CanTargetItems: No
CanTargetTerrain: No
Memory Cost: 1
Magic Cost: 0
TargetConditions: Character

**Comment by ghost** [comment]
Too niche to be an interesting skill.

**Comment by EwayWen** [comment]
Revisiting skill after revision

**Comment by CurtisGouinLo** [comment]
1. Removes: Poison, Diseased, Infected, Decaying Touch, Charmed, Terrified, Madness
2.  Reduce the target's constitution by 1 for 2 turns.
3. Creates a small pool of blood below the target.
4. Range of 2 meters (like Cleanse Wounds)

**Comment by ghost** [comment]
Removed for transfusion.

**Comment by EwayWen** [comment]
^Removed because skill was clunky. And also because Transfusion sounds more fun.
